services:
  backend_wallet:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge



